- hosts: newMachines
  roles:
    - role: cyberark.conjur-host-identity
      conjur_appliance_url: "{{ lookup('env','CONJUR_APPLIANCE_URL') }}"
      conjur_account: "{{ lookup('env','CONJUR_ACCOUNT') }}"
      conjur_host_factory_token: "{{ lookup('env','CONJUR_HFTOKEN') }}"
      conjur_host_name: "{{inventory_hostname}}"
      conjur_validate_certs: true
      conjur_ssl_certificate: "{{ lookup('env','CONJUR_CERT_FILE') }}"
