- hosts: newMachines
  tasks:
    - name: Start application with secrets from Conjur
      shell: "summon --provider summon-conjur ruby test_app.rb"
      args:
        chdir: /usr/src
      environment:
        CONJUR_MAJOR_VERSION: 4
      sudo: true
      sudo_user: root
