- hosts: newMachines
  tasks:
    - name : install Sinatra gem
      shell: "gem install sinatra"
    - name: Start application with secrets from Conjur
      shell: "daemon -- summon --provider summon-conjur ruby test_app.rb"
      args:
        chdir: /usr/src
      environment:
        CONJUR_MAJOR_VERSION: 4
