- hosts: newMachines
  tasks:
    - name: Start application with secrets from Conjur
      shell: "ruby test_app.rb"
      args:
        chdir: /usr/src
      environment:
        CONJUR_MAJOR_VERSION: 4
