- hosts: newMachines
  tasks:
    - name: Start application with secrets from Conjur
      shell: "summon --provider summon-conjur ruby test_app.rb"
      environment:
        CONJUR_MAJOR_VERSION: 4
