---
- hosts: newMachines
  tasks:
    - name : install Sinatra gem
      shell: "gem install sinatra"
    - name: Start application with secrets from Conjur
      shell: "( ( nohup summon ruby test_app.rb 1>/dev/null 2>&1 ) & )"
      args:
        chdir: /usr/src
      environment:
        CONJUR_MAJOR_VERSION: 5
